services:
  comfyui-rocm:
    image: baramofme/comfyui-rocm:rocm7.14-py3.14-torch2.12.0-triton3.7.1-comfy0.33.1
    container_name: comfyui_gpu0
    restart: unless-stopped
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    group_add:
      - video
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    ports:
      - 8189:8188
    environment:
      - LD_PRELOAD=/opt/rocr-fix/libhsa_shim.so:/opt/rocr-fix/libhsa-runtime64.so.1.18.70203
      - CLI_ARGS=--disable-pinned-memory --enable-manager  --use-sage-attention --force-non-blocking --disable-dynamic-vram
      - OMP_NUM_THREADS=8
      - MKL_NUM_THREADS=8
      - OPENBLAS_NUM_THREADS=8
      - VECLIB_MAXIMUM_THREADS=8
      - NUMEXPR_NUM_THREADS=8
      - HSA_ENABLE_SDMA=0
      - HIP_VISIBLE_DEVICES=0,1,2
      - NCCL_P2P_DISABLE=1
      - NCCL_IB_DISABLE=1
      - PYTORCH_TUNABLEOP_ENABLED=0
      - PYTORCH_HIP_ALLOC_CONF=expandable_segments:False,garbage_collection_threshold:0.8
    volumes:
      - /mnt/nvmedata/comfy/rocr-fix:/opt/rocr-fix:ro
      - /mnt/nvmedata/comfy/hf-hub:/root/.cache/huggingface/hub
      - /mnt/nvmedata/comfy/torch-hub:/root/.cache/torch/hub
      - /mnt/nvmedata/comfy/miopen-cache:/root/.cache/miopen
      - /mnt/nvmedata/comfy/miopen-config:/root/.config/miopen
      - /mnt/nvmedata/comfy/models:/workspace/models
      - /mnt/nvmedata/comfy/input:/workspace/input
      - /mnt/nvmedata/comfy/output:/workspace/output
      - /mnt/nvmedata/comfy/user/default/workflows:/workspace/user/default/workflows
      - /mnt/nvmedata/comfy/custom_nodes:/workspace/custom_nodes
    networks:
      - dokploy-network
networks:
  dokploy-network:
    external: true
